apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pms-project
  namespace: argocd
labels:
  owner: platform
spec:
  description: >-
    Argo CD project for PMS applications. Restricts deployments to pms-* namespaces and
    the pms-infra repository.
  sourceRepos:
  - 'https://github.com/pms-org/pms-infra'
  destinations:
  - namespace: pms-dev
    server: 'https://kubernetes.default.svc'
  - namespace: pms-stage
    server: 'https://kubernetes.default.svc'
  - namespace: pms-prod
    server: 'https://kubernetes.default.svc'
  - namespace: monitoring
    server: 'https://kubernetes.default.svc'
  # Do not allow cluster-scoped resources from apps in this project
  clusterResourceWhitelist: []
