apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pms-dev-postgres-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: pms-dev-postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: pms/dev/postgres
      property: username
  - secretKey: password
    remoteRef:
      key: pms/dev/postgres
      property: password
  - secretKey: host
    remoteRef:
      key: pms/dev/postgres
      property: host
  - secretKey: port
    remoteRef:
      key: pms/dev/postgres
      property: port
  - secretKey: dbname
    remoteRef:
      key: pms/dev/postgres
      property: dbname
