apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-capture
  namespace: pms
spec:
  template:
    spec:
      containers:
      - name: trade-capture
        envFrom:
        - secretRef:
            name: trade-capture-secrets