apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      initContainers:
{{ if .Values.initContainers.postgres.enabled }}
      - name: wait-for-postgres
        image: {{ .Values.initContainers.postgres.image }}
        command: {{ toYaml .Values.initContainers.postgres.command | nindent 12 }}
{{ end }}
{{ if .Values.initContainers.rabbitmq.enabled }}
      - name: wait-for-rabbitmq
        image: {{ .Values.initContainers.rabbitmq.image }}
        command: {{ toYaml .Values.initContainers.rabbitmq.command | nindent 12 }}
{{ end }}
{{ if .Values.initContainers.auth.enabled }}
      - name: wait-for-auth
        image: {{ .Values.initContainers.auth.image }}
        command: {{ toYaml .Values.initContainers.auth.command | nindent 12 }}
{{ end }}
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          envFrom:
          - configMapRef:
              name: {{ .Values.service.name }}-config
          - secretRef:
              name: {{ .Values.service.name }}-secrets
          resources: {{ toYaml .Values.deployment.resources | nindent 10 }}