SPRING_PROFILES_ACTIVE=docker
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pmsdb
SPRING_RABBITMQ_HOST=rabbitmq
SPRING_RABBITMQ_PORT=5672
DB_HOST=postgres
DB_NAME=pmsdb
DATASOURCE_HIKARI_POOL_SIZE=20
JPA_OPEN_IN_VIEW=false
JDBC_BATCH_SIZE=500
APP_RABBIT_STREAM_HOST=rabbitmq
APP_RABBIT_STREAM_PORT=5552
APP_RABBIT_STREAM_NAME=trade-stream
APP_RABBIT_STREAM_CONSUMER_NAME=trade-capture-group
SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
KAFKA_BOOTSTRAP_SERVERS=kafka:9092
SCHEMA_REGISTRY_URL=http://schema-registry:8081
SPRING_KAFKA_PRODUCER_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
SPRING_KAFKA_PRODUCER_PROPERTIES_AUTO_REGISTER_SCHEMAS=true
BATCH_SIZE=500
BATCH_TIMEOUT_MS=100