apiVersion: v2
name: leaderboard
description: PMS Leaderboard Service
type: application
version: 0.1.0
appVersion: "latest"

keywords:
  - leaderboard
  - pms
  - microservice

maintainers:
  - name: Platform Team

dependencies: []
