apiVersion: v2
name: schema-registry
description: Confluent Schema Registry for PMS
type: application
version: 0.1.0
appVersion: "7.5.0"

keywords:
  - schema-registry
  - confluent
  - kafka
  - pms
  - infra

maintainers:
  - name: Platform Team

dependencies: []
