apiVersion: v1
kind: Pod
metadata:
  name: db-test-pod
  namespace: default
spec:
  containers:
  - name: postgres-client
    image: postgres:16-alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: pms-dev-postgres-secret
          key: password
