apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: test-secret-k8s
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: test-secret
      property: username
  - secretKey: password
    remoteRef:
      key: test-secret
      property: password
