RABBITMQ_HOST=rabbitmq
RABBITMQ_STREAM_PORT=5552
RABBITMQ_STREAM_NAME=trade-stream
DB_HOST=postgres
DB_NAME=pmsdb
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/pmsdb
SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
KAFKA_BOOTSTRAP_SERVERS=kafka:9092
SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
SCHEMA_REGISTRY_URL=http://schema-registry:8081
SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry:8081
