{{- if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/component: webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: external-secrets
        app.kubernetes.io/component: webhook
    spec:
      serviceAccountName: {{ .Values.aws.irsa.serviceAccountName }}
      containers:
      - name: webhook
        image: {{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
        args:
        - --webhook-server
        ports:
        - containerPort: 9443
          name: webhook
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
{{- end }}