apiVersion: v2
name: frontend
description: PMS Frontend Service
type: application
version: 0.1.0
appVersion: "latest"

keywords:
  - frontend
  - pms
  - microservice

maintainers:
  - name: Platform Team

dependencies: []
