apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.service.name }}
    spec:
      initContainers:
      {{- /* Loop through the dependencies list */}}
      {{- range .Values.deployment.dependencies }}
      {{- if .enabled }}
      - name: wait-for-{{ .name }}
        image: {{ .image }}
        command:
          {{- toYaml .command | nindent 10 }}
      {{- end }}
      {{- end }}
      containers:
      - name:  {{ .Values.service.name }}
        image:  {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy:  {{ .Values.deployment.image.pullPolicy }}
        resources: {{ toYaml .Values.deployment.resources | nindent 10 }}
        envFrom:
        # Global config (DB, Redis, RabbitMQ, Kafka, etc.)
        - configMapRef:
            name: pms-global-config
        # Service-specific config
        - configMapRef:
            name:  {{ .Values.service.name }}-config
        # Global secrets (DB_USERNAME, DB_PASSWORD, etc.)
        - secretRef:
            name: pms-global-secrets
        # Service-specific secrets
        - secretRef:
            name:  {{ .Values.service.name }}-secrets
        ports:
        - containerPort:  {{ .Values.service.targetPort }}
        {{- if .Values.deployment.healthChecks.enabled }}
        {{- include "auth.livenessProbe" . | nindent 8 }}
        {{- include "auth.readinessProbe" . | nindent 8 }}
        {{- include "auth.startupProbe" . | nindent 8 }}
        {{- end }}