apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.service.name }}
    spec:
      initContainers:
{{ if .Values.initContainers.postgres.enabled }}
      - name: wait-for-postgres
        image: {{ .Values.initContainers.postgres.image }}
        command: {{ toYaml .Values.initContainers.postgres.command | nindent 12 }}
{{ end }}
{{ if .Values.initContainers.apigateway.enabled }}
      - name: wait-for-apigateway
        image: {{ .Values.initContainers.apigateway.image }}
        command: {{ toYaml .Values.initContainers.apigateway.command | nindent 12 }}
{{ end }}
      containers:
      - name:  {{ .Values.service.name }}
        image:  {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy:  {{ .Values.deployment.image.pullPolicy }}
        resources: {{ toYaml .Values.deployment.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name:  {{ .Values.service.name }}-config
        - secretRef:
            name:  {{ .Values.service.name }}-secrets
        ports:
        - containerPort:  {{ .Values.service.targetPort }}