{{- if not .Values.secrets.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secrets
  namespace: {{ .Values.service.namespace }}
type: Opaque
stringData:
  DATASOURCE_USER: {{ .Values.secrets.fallback.datasourceUser | default "pms" }}
  DATASOURCE_PASS: {{ .Values.secrets.fallback.datasourcePass | default "password" }}
  JWT_SECRET: {{ .Values.secrets.fallback.jwtSecret | default "change-me-in-production" }}
{{- end }}
