apiVersion: v2
name: simulation
description: PMS Simulation Service
type: application
version: 0.1.0
appVersion: "latest"

keywords:
  - simulation
  - pms
  - microservice

maintainers:
  - name: Platform Team

dependencies: []
