apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - simulation/deployment.yaml
  - simulation/service.yaml
  - trade-capture/deployment.yaml
  - trade-capture/service.yaml
  - validation/deployment.yaml
  - validation/service.yaml

labels:
  - pairs:
      managed-by: kustomize
      component: applications
    includeSelectors: false