apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::209332675115:role/AWSReservedSSO_devx-administrator-access_8d57ac90ee6190f9
      username: devx-admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::209332675115:role/general-eks-node-group-20260107124009170000000007
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
