apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pms-ingress
  namespace: pms
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: pms.local
    http:
      paths:
      - path: /simulation
        pathType: Prefix
        backend:
          service:
            name: simulation
            port:
              number: 4000
      - path: /trade-capture
        pathType: Prefix
        backend:
          service:
            name: trade-capture
            port:
              number: 8080
      - path: /validation
        pathType: Prefix
        backend:
          service:
            name: validation-service
            port:
              number: 8080
